const TEAM = [
    {
        id:1,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:"https://www.google.com"
    },
    {
        id:2,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:3,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:4,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""

    },
    {
        id:5,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:6,
        name:"ashank",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:"https://www.google.com"
    },
    {
        id:7,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:8,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:9,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:10,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:11,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:12,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:13,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:14,
        name:"name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:15,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:16,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:17,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:18,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },
    {
        id:19,
        name:"Name",
        photo:"http://lorempixel.com/output/people-h-g-640-672-6.jpg",
        link:""
    },

    
]

export default TEAM;